// Mocks generated by Mockito 5.4.3 from annotations
// in bluesnap_sdk_example/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bluesnap_sdk/bluesnap_sdk.dart' as _i3;
import 'package:bluesnap_sdk_example/service/api_serivce.dart' as _i7;
import 'package:bluesnap_sdk_example/service/asset_service.dart' as _i5;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T1> extends _i1.SmartFake implements _i2.Response<T1> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BluesnapSdk].
///
/// See the documentation for Mockito's code generation for more information.
class MockBluesnapSdk extends _i1.Mock implements _i3.BluesnapSdk {
  MockBluesnapSdk() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<dynamic> get onGenerateToken => (super.noSuchMethod(
        Invocation.getter(#onGenerateToken),
        returnValue: _i4.Stream<dynamic>.empty(),
      ) as _i4.Stream<dynamic>);

  @override
  _i4.Stream<String> get onError => (super.noSuchMethod(
        Invocation.getter(#onError),
        returnValue: _i4.Stream<String>.empty(),
      ) as _i4.Stream<String>);

  @override
  _i4.Future<void> initBluesnap({
    String? bsToken,
    required bool? initKount,
    String? fraudSessionId,
    String? applePayMerchantIdentifier,
    String? merchantStoreCurrency,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initBluesnap,
          [],
          {
            #bsToken: bsToken,
            #initKount: initKount,
            #fraudSessionId: fraudSessionId,
            #applePayMerchantIdentifier: applePayMerchantIdentifier,
            #merchantStoreCurrency: merchantStoreCurrency,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> finalizeToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #finalizeToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSDKRequest({
    required bool? withEmail,
    required bool? withShipping,
    required bool? fullBilling,
    required double? amount,
    required double? taxAmount,
    required String? currency,
    required bool? activate3DS,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSDKRequest,
          [],
          {
            #withEmail: withEmail,
            #withShipping: withShipping,
            #fullBilling: fullBilling,
            #amount: amount,
            #taxAmount: taxAmount,
            #currency: currency,
            #activate3DS: activate3DS,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> showCheckout() => (super.noSuchMethod(
        Invocation.method(
          #showCheckout,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> checkoutCard({
    required String? cardNumber,
    required String? expirationDate,
    required String? cvv,
    required String? name,
    required String? billingZip,
    String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkoutCard,
          [],
          {
            #cardNumber: cardNumber,
            #expirationDate: expirationDate,
            #cvv: cvv,
            #name: name,
            #billingZip: billingZip,
            #email: email,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [AssetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssetService extends _i1.Mock implements _i5.AssetService {
  MockAssetService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> loadString(String? asset) => (super.noSuchMethod(
        Invocation.method(
          #loadString,
          [asset],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #loadString,
            [asset],
          ),
        )),
      ) as _i4.Future<String>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i7.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i4.Future<_i2.Response<T>>.value(_FakeResponse_0<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<T>>);
}
